# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

before_install:
  - sudo apt-get update > /dev/null
  - pecl install ds
  - composer self-update

before_script:
  - mkdir -p build/logs
  - if [[ "$DB" = "mariadb" ]]; then ./scripts/travis.install.mariadb.sh; fi;
  - if [[ "$DB" = "mysql" ]]; then ./scripts/travis.install.mysql.sh; fi;
  - composer install --no-interaction

script:
  - vendor/phpunit/phpunit/phpunit --configuration ./phpunit.travis.xml test/php

jobs:
  include:
#    - stage: Test
#      php: 7.2
#      env: DB=mariadb
#      addons:
#        mariadb: '10.4'
#
#    - stage: Test
#      php: 7.3
#      env: DB=mariadb
#      addons:
#        mariadb: 10.0
#
#    - stage: Test
#      php: 7.4
#      env: DB=mariadb
#      addons:
#        mariadb: 10.0
#
    - stage: Test
      php: 7.2
      env: DB=mysql

#    - stage: Test
#      php: 7.3
#      env: DB=mysql
#
#    - stage: Test
#      php: 7.4
#      env: DB=mysql


# configure notifications (email, IRC, campfire etc)
notifications:
  email: "info@zf4.biz"

